CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    country_code VARCHAR(2) NOT NULL,
    department VARCHAR(80) NOT NULL,
    job_title VARCHAR(120) NOT NULL,
    job_level VARCHAR(30) NOT NULL,
    annual_salary NUMERIC(19, 2) NOT NULL CHECK (annual_salary > 0),
    currency_code VARCHAR(3) NOT NULL,
    archived BOOLEAN NOT NULL DEFAULT FALSE
);
